# Generated by Django 4.2.23 on 2025-08-08 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprints', '0002_story_sprint_alter_acceptancecriteria_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='task',
            name='story',
        ),
        migrations.RemoveField(
            model_name='story',
            name='epic',
        ),
        migrations.AddField(
            model_name='story',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AcceptanceCriteria',
        ),
        migrations.DeleteModel(
            name='Epic',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
