# Generated by Django 4.2.23 on 2025-08-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_remove_epic_sprint_remove_task_story_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='user',
            new_name='owner',
        ),
    ]
